simavr/cores/sim_mega1280.c
simavr/cores/sim_mega1281.c
simavr/cores/sim_mega128rfa1.c
simavr/cores/sim_mega128rfr2.c
simavr/cores/sim_mega169.c
simavr/cores/sim_mega2560.c
simavr/cores/sim_megax8.h
simavr/cores/sim_megaxm1.h
simavr/cores/sim_tinyx4.h
simavr/cores/sim_tinyx5.h
simavr/sim/avr_adc.c
simavr/sim/avr_adc.h

A patch for ADC free running mode.
It creates the complete framework for other autotrigger modes, such as analog comparator, timer 0 overflow,..
After applying this commit only the free running mode will work, but it won't be difficult adding new modes after this change.
I had to modify the core files as well, as ADTS is different on some AVR-s from the others.
Thanks,
Csaba

Implemented: ADC free running mode

---

simavr/sim/avr_timer.c

If OCR0A is set before the timer configuration in fast pwm mode (WGM00, WGM01, WGM02), it works.
If OCR0A is set after, then the frequency is not changed.
Problematic code:
TCCR0A = _BV(WGM00) | _BV(WGM01);
TCCR0B = _BV(WGM02) | _BV(CS02);
TCNT0 = 1;
TIMSK0 |= _BV(TOIE0);
OCR0A = 0xF9; // this is actually ignored, and timer runs as if it would be 0
The patch calls reconfigure in OCRA write if OCRA is the top.
The patch doesn't fix the very same problem with ICR1 for 16-bit timers. The issue with ICR1 modes are a bit more difficult, so I omitted in this patch.

Reconfigure fast pwm timer at OCRA write  if OCRA is the top

---

simavr/sim/sim_avr.h
simavr/sim/sim_core.c
simavr/sim/sim_regbit.h
tests/atmega2560_uart_echo.c
tests/test_atmega2560_uart_echo.c

This PR introduces a unit test for UART3 usage on the ATmega2560, which first fails because UART3 resides at the end of the IO register space (UDR3 at 0x136) and the core wasn't able to handle these addresses.
It then fixes the issues in the core (mainly replacing 'uint8_t' by 'uint16_t' or 'avr_io_addr_t') and gets the test to pass.

Support IO register addresses >= 256

---

simavr/sim/avr_watchdog.c

Optiboot executes the following statements:
WDTCSR = _BV(WDCE) | _BV(WDE);
WDTCSR = 0;
This should disable the watchdog, but simavr simulator turns it on. The issue is because simavr executes the first statement immediately even if WDCE is not set.

Optiboot bootloader unintentionally enables watchdog

---

simavr/sim/avr_flash.c

bound z to ~(page size - 1), otherwise write may start at anywhere in page to write and fail.
also corrected log line to previous state as was missleading/inacurate.
modified:   simavr/sim/avr_flash.c

flash: be sure to use current page for writing

---

simavr/sim/avr_adc.c

fix issue #118
modified:   simavr/sim/avr_adc.c

adc: check r_adcsrb is valid before init

---

simavr/sim/sim_avr.c

On smaller AVRs, such as the attiny13, MAX_IOs will be larger than the
size of SRAM which will lead to out of range writes to a malloc
allocated buffer. Therefore limit the number of bytes cleared to the
size of SRAM.

Avoid buffer overrun on smaller AVRs

---

simavr/sim/avr_twi.c

> This corrects a problem where a non-interrupt driven twi driver
functions on the target (m32) but not in simavr.
> This also fixes ../examples/board_i2ctest so that it functions as
expected.

twi: Remove start condition delay

---

simavr/sim/avr_twi.c

Fixes the problem that i2c_write returns 1 although the write itself was successful.

Twi i2cwrite fix

---

simavr/sim/sim_core.c

added: _avr_set_r16le and _avr_set_r16le_hl
_avr_set_r16le_hl preserves reverse register set order where used...  not sure if it matters?
two register set calls become a single call.

core: add pair of 16 bit set register functions

---

simavr/sim/avr_timer.c

modified:   sim/avr_timer.c
added: avr_timer_clear_and_cancel_all_cycle_timers
fixes a few oversights in original commit(s)

avr_timer: add avr_timer_clear_and_cancel_all_cycle_timers

---

simavr/sim/sim_core.c

several commits were pushed to a branch which I later split...
one commit had a dependency I missed which this fixes.
modified:   sim/sim_core.c
fix missing dependance in MOVW instruction.

core: fixup missing dependancy from r16 commit

---

simavr/sim/sim_interrupts.c

The variable 'mini' is a FIFO index, not a direct index into the buffer!
Add the current read pointer to fix the operation.
Fixes a regression introduced in 599733f261f94317489c2cc8751fb84fd604e6fa.

sim_interrupts: fix FIFO move operation

---

simavr/sim/sim_gdb.c

When debugging in gdb, if a program uses the watchdog timer to sleep for a period of 1s or greater, an invalid timeval is passed to select() as the timeout.  At least on Mac OS X, this results in select() waiting forever.
This change splits the sleep interval into seconds and microseconds to create a valid timeval.

Support sleep interval of 1s or greater in gdb

---

Makefile.common
simavr/sim/sim_gdb.c

Updated Macports support based on Homebrew support.  Set correct paths
for MacPorts-provided avr-gcc and libelf.

Update support for building with MacPorts

---

Makefile.common

It would probably be cleaner and more flexible, to have LIBELF and AVR_LIBC environment variables, but was wondering what your thoughts on for allowing HOMEBREW_PREFIX ...

Allow for homebrew installed avr-gcc to any prefix

---

simavr/sim/sim_avr.c
simavr/sim/sim_avr.h

Maybe just an idea, because it might leak memory now when avr_set_console_register() is called more than once, but it fixed my problem: Simulating multiple AVRs on a bus in threads, debugging output was garbled because of the static buffer before ...

make console output thread-safe (q&d)

---

simavr/sim/sim_gdb.c

When returning -1 after an error in the `avr_gdb_init` function, `g` is not freed. This is not a big issue but good practice anyway.

Fix a small memory leak when returning after an error

---

README.md

The homebrew instructions, at least on current homebrew, didn't work as the name of the tap was incomplete.
This change should fix that.

Small but crucial fix to Homebrew install instructions

---

simavr/sim/run_avr.c

Listing all the cores by default pushes the basic usage message off the screen for most reasonably-sized terminals.  I have added the "--list-cores" option:
```
$ simavr 
Usage: run_avr [-list-cores] [-help] [-t] [-g] [-v] [-m <device>] [-f <frequency>] firmware
-list-cores: List all supported AVR cores and exit
-help: Display this usage message and exit
-t: Run full scale decoder trace
-g: Listen for gdb connection on port 1234
-ff: Load next .hex file as flash
-ee: Load next .hex file as eeprom
-v: Raise verbosity level (can be passed more than once)
$ simavr -list-cores
[... long list of supported cores ...]
```

Improve usage message by not listing cores by default

---

Makefile.common
simavr/cores/sim_90usb162.c
simavr/cores/sim_mega128.c
simavr/cores/sim_mega1280.c
simavr/cores/sim_mega1281.c
simavr/cores/sim_mega128rfa1.c
simavr/cores/sim_mega128rfr2.c
simavr/cores/sim_mega16.c
simavr/cores/sim_mega169.c
simavr/cores/sim_mega2560.c
simavr/cores/sim_mega32.c
simavr/cores/sim_mega8.c
simavr/cores/sim_megax.h
simavr/cores/sim_megax4.h
simavr/cores/sim_megax8.h
simavr/cores/sim_megaxm1.h
simavr/cores/sim_tiny2313.c
simavr/cores/sim_tinyx4.h
simavr/sim/avr_timer.c
simavr/sim/avr_timer.h

Add an external clock event handler into avr_timer.c and put timer external clock pin definition into every core file, where "TODO: external clock" previously was found.
Also fixes issue #177 . Fixes #178 .
Into avr_timer_t structure added members to store external clock pin and external clock triggering edge:
`avr_regbit_t   ext_clock;  // external clock input pin, to link IRQs`
`uint8_t            ext_edge;   // holds AVR_TIMER_EXTCLK_FLAG_ON, AVR_TIMER_EXTCLK_FLAG_EDGE and other ext. clock mode flags`
Also special value for cs_div member provisioned to mark Clock Select Bit combinations corresponding to the external clock source selection:
`#define AVR_TIMER_EXTCLK_CHOOSE 0x80`
Also external clock handler function avr_timer_irq_ext_clock added to avr_timer.c and few other functions …

Add external clock pin definition and external clocking for timers.

---

simavr/sim/avr_uart.c

Clear interrupt instead of just the rxc bit
Related to issue #189

Workaround for UART issues when polling in some cases

---

simavr/sim/avr_adc.c

ensure that the adsrb is written to memory
process avr_adc_configure_trigger after writing the value to memory
I ran into this when trying to run a modem package that relied on timer trigger in the adc.  This should clean it up a bit to generate logs indicating which modes are supported and not supported.

adc control register write

---

simavr/cores/sim_tinyx4.h

Per ATtiny24A datasheet the `REFS1=0, REFS0=1`  indicates **AREF** pin. Unlike on most mega cores where it is `AVCC`.
Table 16-3:  Voltage Reference Selections for ADC:
```
REFS1  REFS0 Voltage Reference Selection
0 0  VCC used as analog reference, disconnected from PA0 (AREF)
0 1  External voltage reference at PA0 (AREF) pin, internal reference turned off
1 0  Internal 1.1V voltage reference
1 1   Reserved
```

Tinyx4 core, avcc->aref

---

simavr/cores/sim_core_declare.h
simavr/sim/sim_avr.c
simavr/sim/sim_avr.h

http://www.atmel.com/images/doc2551.pdf
This application note has some recommendations for productiin quality firmware that uses watchdog timer. In particular, on page 11, the diagram recomnends checking MCUSR (MCUCSR on some) register for reset flags. If no reset flag is set then there was no genuine reset and the code ended up at address zero due to a bug.
In order to be able to test how furmware behaves with different reset conditions and, more importantly, get firmware that follows the above algo to work with simavr I suggest this pull request. It basically exposes some of the most common reset flags and also sets PORF (power-on reset flag) by default.

Add reset flags and set power-on reset as a default when avr is initialised

---

simavr/cores/sim_90usb162.c
simavr/cores/sim_mega128.c
simavr/cores/sim_mega1280.c
simavr/cores/sim_mega1281.c
simavr/cores/sim_mega128rfa1.c
simavr/cores/sim_mega128rfr2.c
simavr/cores/sim_mega169.c
simavr/cores/sim_mega2560.c
simavr/cores/sim_megax.c
simavr/cores/sim_megax.h
simavr/cores/sim_megax4.c
simavr/cores/sim_megax4.h
simavr/cores/sim_megax8.c
simavr/cores/sim_megax8.h
simavr/cores/sim_tiny13.c
simavr/cores/sim_tiny2313.c
simavr/cores/sim_tinyx4.c
simavr/cores/sim_tinyx4.h
simavr/cores/sim_tinyx5.c
simavr/cores/sim_tinyx5.h
simavr/sim/avr_acomp.c
simavr/sim/avr_acomp.h
simavr/sim/avr_timer.c
simavr/sim/avr_timer.h
tests/atmega88_ac_test.c
tests/test_atmega88_ac_test.c

I have added implementation of the analog comparator for all parts, apart from megaxm1 family, as it is completely different there.
It supports all the features including triggering input capture on a timer. For this I had to make a small change in the timer implementation to have a separate input capture irq that is connected to the relevant port pin irq, instead of just registering notifications from the port. This allows triggering of the capture independently from the port.
Comprehensive tests added too.

Add analog comparator

---

simavr/Makefile

For example, before this change the version would
be set as 'tag:v1.5'. After this change it will be
'v1.5'.

misc: Strip off tag prefix from the pkg-config version

---

simavr/sim/sim_hex.h

'size_t' is not defined in any of the header files included in
'sim_hex.h', even though it is used in there.
Without this, you cannot parse `sim_hex.h` on its own.
You can see a list of all headers that define 'size_t' here
http://en.cppreference.com/w/c/types/size_t

Add missing header file to 'sim_hex.h'

---

Makefile
examples/parts/Makefile
simavr/Makefile
simavr/simavrparts.pc

An external project using simavr can link against libsimavr.
However, there is no support for using virtual parts from the
examples folder in the external project.
This commit adds support for building a parts library, which the
external project can link against. Presently this library is fairly
small, but as the number of parts grows this approach may need
to be changed. A longer term solution could be to provide an API as
part of the simavr library which can manage the parts. Simavr could
dynamically load and provide parts as required by the external
project.
Like libsimavr, this patch makes no attempt to make the version easy
to set. That can be covered under a different PR.

parts: Build a simavr virtual parts library

---

simavr/cores/sim_tiny2313a.c
simavr/cores/sim_tiny4313.c
simavr/sim/avr_eeprom.h

I added 2 new corefiles to support the attiny2313a and the attiny4313.
I also modified the avr_eeprom.h file, because some iotnxx.h files doesn't have an EEARL definition (only an EEAR definition).

new corefiles: attiny2313a and attiny4313

---

Makefile.common

Installation via homebrew does not work at all (some odd failure that I don't really understand), so I downloaded the source. I had to make a couple of alterations to the makefile to get it to work.
-Werror causes the compilation to fail because of warnings about deprecated functions in the Mac's GLUT OpenGL libraries. As these problems are not that important I just removed it and it seems to work fine. However, I'm sure it's there for a reason...
The other change was that the path to the AVR libraries within the Arduino IDE bundle was not correct (perhaps it has changed over time?) so none of the cores worked for me. With these 2 changes it all compiled and seems to work.

A couple of alterations to make it work on OS X

---

Makefile

Currently parallel builds fail every time for me (output provided). This seems to be related to the examples and parts stomping over each other.
```
CC charlcd.c
error: unable to open output file 'obj-x86_64-apple-darwin16.7.0/charlcd.o': 'No such file or directory'
1 error generated.
make[2]: *** [obj-x86_64-apple-darwin16.7.0/charlcd.o] Error 1
make[2]: *** Waiting for unfinished jobs....
2122      14       5    2141     85d atmega48_charlcd.axf
AVR-CC atmega1280_i2ctest.c
CC i2ctest.c
error: unable to open output file 'obj-x86_64-apple-darwin16.7.0/i2ctest.o': 'No such file or directory'
1 error generated.
make[2]: *** [obj-x86_64-apple-darwin16.7.0/i2ctest.o] Error 1
make[2]: *** Waiting for unfinished jobs....
1208      16      12    1236     4d4 atmega1280_i2ctest.axf
AVR-CC …
```

Make parallel builds succeed

---

examples/board_timer_64led/timer_64led.c
simavr/sim/avr_adc.c
simavr/sim/sim_avr.h
simavr/sim/sim_core.c

Since avr-gcc version 7 the flag -Wimplicit-fallthrough is set, so that a missing "break;" inside a switch-case statement will throw an error in the compiling process.
The missing breaks are now replaced by the FALLTHROUGH define and no errors occours.
The FALLTHROUGH is simply an "__attribute__((fallthrough));" - if it is supported by the compiler (defined in sim_avr.h).
The commit 88b50bb (removing -Werror) didn't fixed the issue #239.
The define FALLTHROUGH is tested with avr-gcc 7.1.0 and 4.4.5.

Added a define "FALLTHROUGH" to suppress 'this statement may fallthrogh' messages

---

simavr/cores/sim_mega32u4.c

florent.n.poulain@gmail.com is the author according to this post:
<https://groups.google.com/d/msg/simavr/oc2vjBccUYo/C_8aWlni-M4J>
@buserror This core definition was found online as-is complete with copyright notice, can it be included upstream?

Add support for atmega32u4 core

---

simavr/sim/avr_extint.c

avr_extint_exists() is used to establish if an extint index is valid
and avr_extint_count() is removed because it is not used any longer.

extint: support cores with non-contiguous extint numbers like atmega32u4

---

examples/parts/ssd1306_virt.c

Without this change receiving SSD1306_VIRT_CHARGE_PUMP will
make the command parser get out of sync.

ssd1306_virt: add SSD1306_VIRT_CHARGE_PUMP command (ignored)

---

examples/board_ssd1306/ssd1306demo.c
examples/parts/ssd1306_glut.c

* A couple of fixes
* Instead of adding vertical and horizontal flipping flags as in https://github.com/buserror/simavr/pull/251, let the board setup a suitable projection matrix.

ssd1306 fixes and improvements

---

simavr/sim/avr_uart.c
simavr/sim/avr_uart.h

This is often used to indicate a break condition when it comes with zero data too. In fact, this is what I needed this for. I changed the fifo to use 16-bit entries, so that higher byte can contain the flags. This can later be extended to support 9-bit words too.

Add support for  framing error in uart

---

simavr/cores/sim_megaxm1.h
simavr/sim/avr_uart.c
simavr/sim/avr_uart.h

I'm unsure if it's applicable on every AVR type

use only 12 bits for ubrr

---

simavr/cores/sim_core_declare.h
simavr/cores/sim_mega128.c
simavr/cores/sim_mega1280.c
simavr/cores/sim_mega1281.c
simavr/cores/sim_mega128rfa1.c
simavr/cores/sim_mega128rfr2.c
simavr/cores/sim_mega169.c
simavr/cores/sim_mega2560.c
simavr/cores/sim_mega32u4.c
simavr/cores/sim_tiny13.c
simavr/cores/sim_tiny2313.c
simavr/cores/sim_tiny2313a.c
simavr/cores/sim_tiny4313.c
simavr/cores/sim_usb162.c

For some parts sim_core_declare.h ends up included before the relevant AVR header. As a result ifdefs, such as ifdef SIGNATURE_0 is never true and stuff ends up missing

Make sure sim_core_declare.h is included *after* avr includes

---

simavr/cores/sim_mega2560.c
simavr/sim/avr_timer.c
simavr/sim/avr_timer.h

According to documentation, modes 14 and 15 for timers 1, 3, 4 and 5 are, respectively, Fast PWM with TOP = ICRn and Fast PWM with TOP = OCRnA. Current code considered them regular PWM, and accordingly (avr_timer.c:579) set their TOP to the "size" value, which is undefined for these modes.
It happened I needed mode 14. I'm simulating an Arduino Mega board, and my Arduino program uses the Adafruit_TiCoServo library. This lib uses mode 14 to generate a PWM pulse to control servos, so as not to rely on interrupts as the Arduino Servo lib does.
I only fixed mode 14 (mode 15 should be straightforward too, but I don't have time to test it) and only tested it with timer 3, though there's no reason it shouldn't work with other timers.
I can provide a simple test case if needed, when I have the …

Fix timer mode 14 for timers 1, 3, 4 and 5 on Atmega2560

---

simavr/Makefile

On some systems, including some Mac and some Linux computers, the
sim_core_config.h file will not have any cores compiled on it.
Here is the patch from #20.
I have tested this on Linux, and there are many people on #20 reporting
that it works perfectly on Mac.

Fix a bug which causes no cores to be compiled

---

simavr/cores/sim_megax8.h

In all of the datasheets for ATmega44/88/168/328 devices that I've
seen, there are 8 channels of ADC selected with MUX modes 0000-0111,
and the temperature sensor is selected with MUX mode 1000.
Fixes #167

Correct x8 ADC mux modes

---

simavr/sim/sim_gdb.c

Someone pointed out to me that the gdb command "info registers SREG" can return incorrect output if not preceded by a "info registers" call to refresh all registers.  
I tracked this down to the code in gdb_send_quick_status() that seems to use an incorrect or obsolete method to get SREG and push it over to gdb.  I copied over the gdb_read_register version, which used READ_SREG_INTO and seemed to be correct.
This may be unnecessary if your sreg-inline changes alter how the status register is stored, but I suspect it is safe either way.

use READ_SREG_INTO rather than g->avr->data[R_SREG] in sim_gdb.c

---

examples/board_rotenc/Makefile
examples/board_rotenc/README
examples/board_rotenc/atmega32_rotenc_test.c
examples/board_rotenc/rotenc_test.c
examples/parts/rotenc.c
examples/parts/rotenc.h

Add a rotary encoder virtual part, based on the Panasonic
EVEP rotary encoder. This could easily be extended to virtualise
other rotary encoders.
Add a demo board. This connects an LED bar up to an ATMega, and
uses the rotary encoder to scroll an LED up and down the bar.
I noticed a whole bunch of interrupts fire when they *probably* shouldn't when the board turns on. I haven't got to the bottom of it yet, but I don't *think* the issue originates in this PR. After the board is on, it behaves as expected.

Rotary encoder and demo board

---

simavr/sim/run_avr.c

As described in issue #293 GCC 8 fails the build in the current
configuration on warnings like:
sim/run_avr.c:193:4: error: ‘strncpy’ specified bound 128
equals destination size [-Werror=stringop-truncation]
strncpy(f.tracename, argv[++pi], sizeof(f.tracename));
This isn't the only solution, but it get's the build working.
```$ make
make -C simavr RELEASE=0
make[1]: Entering directory '/home/doug/git/simavr/simavr'
make obj config
make[2]: Entering directory '/home/doug/git/simavr/simavr'
make[2]: Nothing to be done for 'obj'.
make[2]: Nothing to be done for 'config'.
make[2]: Leaving directory '/home/doug/git/simavr/simavr'
make libsimavr run_avr
make[2]: Entering directory '/home/doug/git/simavr/simavr'
make[2]: Nothing to be done for 'libsimavr'.
CC sim/run_avr.c
sim/run_avr.c: In …
```

Forcibly null terminate input strings

---

simavr/cores/sim_mega32u4.c

For #276 Mismatch in define casing causes RAMEND to not match.

Fix atmega32u4 RAMEND

---

examples/parts/uart_pty.c

After fifo overrun buffer_done remains less than buffer_len and
FD_SET(p->port[ti].s, &read_set) is not called. If firmware has nothing
to send, select always returns 0 and new data is never read even if
fifo buffer gets flushed.
This patch removes check for select timeout, so the remaining data in
buffer may go to fifo.

Fix receiving after fifo overrun

---

simavr/cores/sim_tinyx5.h

The prescaler list for timer1 on the tinyx5 was incomplete. Moreover,
having no WGM data made the timer run in `avr_timer_wgm_none`, with a
zero size (it would overflow all the time).
Setting a default wgm_op makes time timer run in normal mode witha size
of 8 bits.
I have a program to reproduce the problem at https://github.com/hsoft/avr-asm/tree/master/timer1_tn45 . When I load this program on a real attiny45, PB0 blinks properly.

Fix timer1 on tinyx5

---

simavr/cores/sim_tiny13.c

The "settings" .com and .com_pin settings for timer0 in section .comp were missed, so the OC0A / OC0B toggling (or the other modes) never occured.

added OC0A/OC0B support for attiny13

---

README.md

I've found that there is a maintainer who publishes SimAVR for Ubuntu here:
https://packages.ubuntu.com/bionic/simavr
Seems to be kept reasonably up-to-date (the latest there is 1.15 whereasy here on GitHub it is 1.16).
I know that maintainers do not always keep in contact with the software vendor so I would not be surprised to learn you were not aware of this. If you are okay with it though and consider it to be a legit enough source, I figure it's good to call that out in the README.
BTW this probably also works on Debian, but I didn't try it there so I stuck to what I knew for a fact worked.

Note that it is possible to install through Aptitude

---

simavr/sim/sim_gdb.c

LLDB requires the qRegisterInfo packet to work correctly. While it is possible to specify the registers manually using a Python script, having them directly in the emulator simplifies things a lot.
AVR support for LLDB is still a work in progress, but I managed to get very basic support working with this patch to simavr:
You will need a very recent version of LLDB, basic support was merged only a few days ago. Also, you'll need to use avr-gcc with `-gdwarf-4`:
avr-gcc -o tmp/avr-nop.elf -Og -gdwarf-4 tmp/avr-nop.c

Add support for debugging with LLDB

---

simavr/sim/sim_core.c

Fix a bug in the bitmask of _avr_is_instruction_32_bits() function which can lead to misinterpret certain opcodes length.
For example:
sbiw r24, 0x1c   (1001 0111 0100 1100) (0x974c)
with current bitmask: (0xfc0f)
1001 0111 0100 1100 &
1111 1100 0000 1111 =
1001 0100 0000 1100  (0x940c)
0x940c matches as JMP in _avr_is_instruction_32_bits() function which has 32 bits opcode,
but SBIW has a 16 bit opcode, so the function interprets SBIW as an instruction with a 32 bits opcode.
The proposed new bitmask is 0xfe0f.

Fix a bug in the bitmask inside _avr_is_instruction_32_bits() function in sim_core.c file.

---

simavr/sim/sim_core.c

In _avr_set_ram, we check if the address is smaller than `MAX_IOs + 31`
to know if it is a register or SRAM location.  In reality, many devices
have less I/Os than that, so the SRAM begins before this address.
As shown in issue #372, this causes watchpoints to not be triggered when
writing to an SRAM location that is smaller than `MAX_IOs + 31`.  For
example, a global variable on an atmega328 gets placed at address 0x100,
which is less than `MAX_IOs + 31`.
Fix this by comparing the address to the `ioend` property of `avr`.
Fixes #372

Compare address with I/O end address in _avr_set_ram

---

simavr/sim/avr/avr_mcu_section.h

Fix for issue #285, #378.
Follows the suggestion from https://gcc.gnu.org/wiki/LinkTimeOptimizationFAQ

used attribute for _MMCU_ , should avoid dropping the .mmcu section

---

simavr/sim/sim_gdb.c

new gdb commands kill, detach and monitor
monitor parser supports reset and halt words but can be easily extended
improves [integration](https://community.platformio.org/t/avr-simulator-as-aid-tool-for-debugging-code/13444) into development environments like PlatformIO
fix issue #370

Support for GDB monitor commands

---

simavr/cores/sim_mega2560.h
simavr/sim/avr_ioport.c
simavr/sim/sim_interrupts.h

Some chips have PCINT setups that are not aligned with ports. 
For example, the 2560 has PCINT8 on E0, and PCINT9-15 on J0-6
This adds a mask and shift option to the PCINT declaration to support this. 
The default mask behaviour is that if mask = 0 (no PCINTs, this doesn't make sense in a normal context) then the behaviour is as before. If mask and/or shift are defined, the bitfield is shifted appropriately to align it with the expectation for the & with irq->irq. 
Also includes a fix for PORTJ on the 2560 to enable its PCINTs using this.

Support for non-aligned PCINTs

---

simavr/sim/avr_spi.c
simavr/sim/avr_spi.h

This removes the hard-coded 100 uS SPI out delay and calculates the correct delay based on the configured
clock divisors in SPSR/SPCR.

Clock out SPI data according to SPCR/SPSR

---

simavr/sim/avr_timer.c
simavr/sim/avr_timer.h

Another small feature-fix I cherry picked to contribute upstream.
Adds a PWM2 output IRQ for AVRs with a third comparison pin/register, like the 2560.

Support 3rd PWM pin on timers with OCRxC

---

examples/parts/button.c
examples/parts/button.h

This allows better control of key press length, if needed.
To minimize negative effect on existng code, if the duration
argument of button_press is non-zero, functionality is kept as is
(i.e., using auto-release). If duration is set to zero, then button
will have to be explicitly released using a new API function,
button_release.
If simulation uses GLUT, it may make use of glutKeyboardUpFunc and
glutIgnoreKeyRepeat (in addition to glutKeyboardFunc found in
existing examples) to have more exact control over button presses
and releases.

Add support for non-auto release to button

---

simavr/sim/avr_uart.c

modified:   sim/avr_uart.c
Previously, disabling the uart transmitter cleared the udrc
interrupt and cleared the udre (udrc.raised) flag.  Upon
reenabling the transmitter, the udre flag is still clear
signifying the buffer is full, thus waiting for the udr to
clear via udre flag hangs.

Set udre flag when (re)enabling uart transmitter.

---

Makefile.common

That is the usual way and allows it to be easily loaded by dlopen().

Link libsimavr.so with needed libraries.

---

simavr/sim/sim_avr.h
simavr/sim/sim_elf.c

Adding a size field makes it easier to extract and inspect sections from a given elf_firmware_t.

Add size property to avr_symbol_t

---

simavr/sim/sim_hex.c

Per #446 - there is a minor bug with multipart hex files because the segment is not reset to 0 when an "end of file" marker is reached. This causes the first segment of the next file to get an incorrect base address, and incorrectly breaks it into multiple chunks as well. 
Closes #446

Fix #446 - bug in multipart ihex

---

Makefile.common

Versioned homebrew installations are postfixed with @ (e.g. avr-gcc@9). The current makefile doesn't recognise these intallations as avr-gcc, so this PR fixes that.

Fix macos build with versioned avr-gcc

---

simavr/cores/sim_mega32u4.c
simavr/sim/avr_timer.c
simavr/sim/avr_timer.h

I found a few discrepancies between `simavr` and the ATmega32U4 datasheet regarding the behaviour of the "output compare" outputs, so I've had a go at fixing them.
I'll admit I'm not very familiar with `simavr` or these microcontrollers, so I hope I haven't broken anything.

Improve functionality of timers

---

simavr/sim/sim_avr.c
simavr/sim/sim_avr.h
simavr/sim/sim_core.c
simavr/sim/sim_gdb.c
simavr/sim/sim_gdb.h

Addition of load command fixes #371.  The "awatch" command now works and "break" instructions are useable without having to make gdb jump over them by hand.  General gdb behaviour is improved by not sending confusing stop reports.  Other bug fixes as described in the commit comments, including an equivalent to the fix in #480.

Gdb: add support for "load" and "info_registers" and fix bugs.

---

examples/board_simduino/simduino.c

On line 130, the `mmcu` and `freq` are updated to reflect the identified change in part.  But the `avr` has already been initialized, so it doesn't get the new values.  This change delays initializing the `avr` until we've picked with core to use.

simduino: wait to init avr until we pick a core

---

simavr/sim/avr_watchdog.c

WDIE must be automatically cleared only in "Interrupt and System Reset Mode" (where it's used to transition to "System Reset Mode").
In other modes, watchdog interrupt must not clear WDIE.
Strictly speaking, the modified condition also clears it in "System Reset Mode" as well, but the system is reset on interrupt anyway, so it doesn't matter.
See #456

Fix WDIE being wrongly cleared in Interrupt Mode

---

examples/parts/hd44780.c
examples/parts/hd44780.h
examples/parts/hd44780_glut.c

- Fix the virtual memory of the HD44780 part
In HD44780, the DDRAM has an address space of 0x80 bytes, while
CGRAM has 0x40 bytes. To ensure their proper separation, the vram
should have 0x80+0x40 bytes with the CGRAM starting at 0x80.
- Fix cursor handling in segmented DDRAM of HD44780
HD44780 has only 80 bytes of DDRAM, which consists of two 40 bytes
long segments. The segment starting at address 0x00 contains the
data for the first line of the display, while the segment starting
at address 0x40 contains the data for the second line of the
display. This means that there are invalid ranges in the 7-bit
address space of the DDRAM (0x00+40 .. 0x3f and 0x40+40 .. 0x7f).
The cursor (address counter) of the HD44780 automatically "jumps
over" these regions whenever …

Fixes to HD44780

---

simavr/sim/sim_avr.c

Firmware output to stdout and diagnostics to stderr seem correct.

Correct output streams for logging output.

---

simavr/cores/sim_tiny13.c
simavr/sim/sim_core.h

Makes the tiny13 work again and fixes an error in #482: building with tracing enabled is currently broken (found while verifying #421 fix).

Fix #421 (Tiny13) and an error in PR #482

---

simavr/sim/sim_interrupts.c
tests/attiny44_interrupt_irq_test.c
tests/test_attiny44_interrupt_irq_test.c

This PR is a re-creation of the earlier PR #481 (auto-deleted on branch removal), based on a new branch with the same change recreated at the current head of buserror/simavr/master.  It should merge cleanly.
Make the global interrupt pending IRQ behave consistently, so that the
value is always a vector number.  Make the floating flag more useful;
when set it indicates the next interrupt expected.  Remove a call
that added no information.  Add a test.

Interrupt IRQs: improve consistency and add a test.

---

simavr/sim/run_avr.c
simavr/sim/sim_hex.c
simavr/sim/sim_hex.h
tests/Makefile
tests/test_atmega88_hex.c
tests/tests.c
tests/tests.h

Pull the .hex loading code out of run_avr.c and make it available as
a function, sim_setup_firmware(), that also handles ELF firmware.
Add a test, test_atmega88_hex.c, and use the new function in other tests.
This replaces #466.

Combined function for loading ELF or ihex firmware.

---

simavr/cores/sim_tinyx5.c
simavr/cores/sim_tinyx5.h
tests/attiny85_spm_test.c
tests/test_attiny85_spm.c

The ATtinyx5 MCUs are able to self-program.
There is no RWW section, and no SPM interrupt on these chips

Enable self-programming for attinyx5

---

simavr/sim/avr_uart.c

Previously, when accessing the `p->fe.reg` in `avr_uart.c` (in `avr_uart_init()`) for ATmega16m1, the system segfaulted.
In avr_register_io_read, we see the following lines:
```c
avr_io_addr_t a = AVR_DATA_TO_IO(addr);
if (avr->io[a].r.param || avr->io[a].r.c) {
```
`AVR_DATA_TO_IO` just subtracts `0x20` from `addr`. `addr` is passed in from `avr_uart_init` as `p->fe.reg`. But in ATmega16m1, `p->fe` is not initialized, so it is set to zero. When we subtract `0x20` from `0`, and then do `avr->io[a]`, we have an array-out-of-bounds error.
The following previously segfaulted, but no longer does:
```shell
./simavr/run_avr -m atmega16m1 -f 4000000 ~/path/to/binary.elf
```

Fix segfault with ATMega16m1 UART simulation

---

simavr/sim/sim_gdb.c

When debugging the compiled program with avr-gdb, the `next` and `step` instructions always step only one machine instruction instead of stepping to the next source line. When the simulator finished the gdb client's step request, it responds that the program halted because of "signal 0". If I replace this with "signal 5, hardware breakpoint", avr-gdb works as expected. This effectively simulates that stepping is implemented with an automatically managed hardware breakpoint.
In [examples/board_timer_64led/timer_64led.c:270](https://github.com/buserror/simavr/blob/7003af00df0f89a38898896fe536c5f15ae4ef1a/examples/board_timer_64led/timer_64led.c#L270) enable debugging and uncomment the next line (set the CPU state to stopped).
Build the project and run the `./atmega168_timer_64led.axf` …

Fix step and next instructions in avr-gdb debugging

---

simavr/sim/avr_flash.c

Introduced in commit 3bb6c1d, these debug messages get mixed with output from the program being tested.
I'm using simavr (thanks for the great project!) in continuous integration testing, so the extra prints confused the automated test logic.

Comment out forgotten debug messages.

---

simavr/sim/avr_eeprom.c
simavr/sim/avr_flash.c
simavr/sim/sim_elf.c
simavr/sim/sim_elf.h
simavr/sim/sim_hex.c

The flash ioctl handler unconditionally reported the request as processed even when it was skipped. This lead to eeprom ioctl handler not getting called at all if it was registered later than the flash.
The eeprom ioctl handler reported the request as not processed even if it was, so fix that too while at it.
This bug resulted in the emulated firmware seeing blank EEPROM even when the contents was provided (as a section in ELF or as a separate HEX file) and r/w access via GDB not working.

flash+eeprom: fix ioctl handling

---

examples/board_simduino/Makefile
examples/board_simduino/simduino.c

[examples/board_simduino](https://github.com/buserror/simavr/tree/26375838c521c60280ebdf205d17bb8b2e4fde47/examples/board_simduino) depends on OpenGL but does not actually use it. This small pull request removes the GLUT include/link. `git blame` shows that OpenGL code was included in simduino.c originally (https://github.com/buserror/simavr/commit/0a764c4ef24512959bcbb47eb905470a113fa856) and removed in commit https://github.com/buserror/simavr/commit/f6363b60812be10c6bf9fc9793dfee636a7d223b without removing the GLUT headers and linking.
I noticed this while working on a minimal Docker image for a text-only arduino simulator using simavr.

simduino: remove GLUT dependency

---

.github/workflows/build.yml
simavr/sim/sim_avr.c

Successfully test-compiles for
* Windows 64-bit (using MSys2)
* Windows 32-bit (using MSys2)
* Linux x64
* Linux x86
* Linux ARM (ARMv6l, ARMv7l, AArch64, a.k.a, Raspbis)
* Mac OS 14 ([source](https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners/about-github-hosted-runners))
And uploads the binary packages for it. They were tested to run a firmware fine on Windows.
Includes a tiny compilation fix for Windows based builds which apparently don't have the `random()` function (only available on Unix-like systems), so uses `rand()` instead. Breakage introduced in https://github.com/buserror/simavr/commit/3bb6c1d455e0f3f374261917ceaea1fab40b53a9.
Please squash upon merge to not have 10 commits.
For the run logs, see e.g. …

Add Github Action CI + Windows compile fix

---

.github/workflows/build.yml

Fixes CI failures by
* downgrading to Ubuntu 22.04 for the 32-bit Linux build
* doing `sudo apt-get update` in the Raspberry Pi builds
Gets all the green checkmarks back.

Fix CI again

---

simavr/sim/avr/avr_mcu_section.h
simavr/sim/avr_adc.c
simavr/sim/run_avr.c
simavr/sim/sim_avr.h
simavr/sim/sim_core.c
simavr/sim/sim_elf.c

Add support for 8 & 16 bits SRAM traces (0x20-ramend, i.e. overlap IO range to handle 16 bits registers)
SRAM tracing allows tracking of 16 bits registers, e.g. SP (Stack Pointer) as well as firmware variables, e.g. __brkval (Heap), that have no fixed adresses (using new AVR_MMCU_TAG_VCD_SRAM_8 and AVR_MMCU_TAG_VCD_SRAM_16 macro to populate the avr_mmcu_vcd_trace_t in the .mmcu section).
This has been developped to analyze heap-stack margin and evolution over time in the following project: https://github.com/jpcornil-git/Cone2Hank.
VCD trace example:
https://github.com/jpcornil-git/simavr/tree/master/examples/board_sh1106#examples

Add support for 8 & 16 bits sram traces

---

examples/board_hd44780/Makefile
examples/board_hd44780/atmega48_fps_test.c
examples/board_hd44780/charlcd.c
examples/parts/hd44780.c
examples/parts/hd44780.h
examples/parts/hd44780_glut.c
examples/parts/hd44780_glut.h

The example code for the LCD display uses two threads: one for simulating the AVR chip, and one for OpenGL. The state of the LCD display is stored as some flags in a `uint16_t` variable. When the OpenGL thread modifies a flag, it may accidentally undo a simultaneous write operation in the AVR thread, causing malfunction of the display.
In this PR I add mutex support to the LCD chip simulation. The pthread library is only included in the OpenGL-related parts of the code, so it is still possible to compile the LCD simulation itself without the threading library.
The introduction of this mutex does not noticeably affect performance.
The LCD display is stored in a struct `hd44780_t`. This struct has a 2 byte integer member which contains various bit flags. One flag is for the internal status: …

Fix data race when rendering an LCD display

---

simavr/sim/sim_hex.c

1. Linked list uses realloc but did not update the pointer in the previous linked list item
resulting in Use-After-Free error. A backlink_p
local variable is introduced to update the pointer address after a reallocation.
2. The local variable chunks_p was not updated after realloc which also resulted in UAF when
allocating a new element to the linked list.
A refreshing of the address was added after realloc.

Fix two UAF errors in read_ihex_chunks()

---

.github/workflows/build.yml

The [CI build on AArch64][ci] is failing on “No space left on device” errors. The failing step is defined as:
```yaml
uses: pguyot/arm-runner-action@v2
with:
cpu: cortex-a53
base_image: raspios_lite_arm64:latest
image_additional_mb: 1024  # NOTE: because of this...
commands: |
df -h /                  # ...this should report at least 1 GiB free
[...]
```
The `image_additional_mb` parameter has no effect: increasing the value does not fix the failure, and the `df` command reports only 143 MiB free.
It turns out pguyot/arm-runner-action attempted to resize the filesystem, but failed to do so. This is because the `raspios_lite_arm64:latest` image uses the quite new [“Orphan file” feature of ext4][orphan], which is not supported by the e2fsprogs 1.46.5 package shipped with the Ubuntu 22.04 …

Fix CI failure on AArch64
