Makefile.common, simavr/Makefile
Added support for compilation using avr-libc and libc3 sources in homebrew's cellar.
=> added support for MacOSX homebrew

simavr/sim/sim_core.c
modified:   sim/sim_core.c
added _avr_flash_read16le accessor function
changed "avr->flash[addr] | (avr->flash[addr + 1] << 8)"
to "_avr_flash_read16le(avr, addr)"
**** a few line notes were left in the commit...  several big endian accesses were used where, unless I am missing something, I believe little endian was ultimately intended.  I presume little endian was intended as the update reflects.
=> core: change 16 bit flash access

simavr/sim/avr_extint.c, simavr/sim/avr_extint.h
=> Triggering by level for external interrupts

simavr/sim/avr_ioport.c
=> Provide IRQs on PORT register when updated via PIN

simavr/sim/sim_gdb.c
Fixes #179, fixes #150 .
These changes are of high importance to me, because I'm writing GUI wrapper for simavr: ([see discussion there](https://groups.google.com/forum/#!topic/simavr/94w3SzSsNgc), where user can start and stop debugging repeatably.
=> sim_gdb: fix for restore callbacks issue

simavr/sim/avr_eeprom.c
=> Add EEPROM address boundary checks for read/write operations

simavr/sim/avr_timer.c
timer with ocr 0 is never triggered
=> fix timer is not triggered at ocr==0

simavr/sim/run_avr.c, simavr/sim/sim_vcd_file.c
Some log statements were seemingly never executed,
Some would be nice to add.
=> Improve logging

simavr/sim/sim_core.c
=> On actual hardware, memory accesses seem to wrap.

simavr/sim/sim_interrupts.c
=> allow polling interrupt flag within ISR

examples/Makefile.opengl, examples/parts/Makefile, examples/parts/uart_pty.c, simavr/sim/sim_avr.c
Tested on FreeBSD 11.2-RELEASE
=> Make simavr build on Freebsd

Makefile.common
=> Also search for /usr/lib64/librt.so

simavr/sim/sim_vcd_file.c
This solves issue 325 by converting timescale of vcd input to internal timescale of micro seconds. It will print an error message if the timescale is both, less then us and not dividible by 1000 without loss.
=> #325 Converts timescale from vcd input to internal us.

simavr/cores/sim_mega64m1.c
Link the existing "avr/iom64m1.h" with the atmega64m1 core
=> Add ATMega64M1

tests/tests.c
Fixes issue https://github.com/buserror/simavr/issues/365
=> Don't assign stderr on non-glibc

simavr/sim/run_avr.c
Some arguments changed name to make them more like the already existent ones.
Some arguments were merged to one to reduce redundant code.
Fix issue #375
=> Update of the display_usage function.

simavr/sim/avr_adc.c, simavr/sim/avr_adc.h
Fix #383 - Enable read IRQs for ADCs > 7
=> Fix ADCs>7

simavr/sim/avr_twi.c
Just a partial commit that fixes two of the issues with higher speed TWI:
- Wrong ACK type on write - we'd go down the wrong execution path on writes because both TWI_COND_WRITE and TWI_COND_ADDR were true. Checking TWI_COND_ADDR first resolves this.
- Implemented correct calculation of the TWI Status register delay for >100KHz rates. 
Pending: 
- Still an outstanding bug with TWINT not being cleared while the TWI simulation is "busy". (see comment on #137) but I think these fixes are beneficial to get in without resolving that first.
Tested against code that's been verified on real hardware.
=> Fix high speed TWI delay calcs and ACK bug (#137)

simavr/cores/sim_megax4.h
according to datasheet, tested with some code that works on real device (1284P)
=> megax4: fix INT2 pin

simavr/cores/sim_mega328pb.c, simavr/cores/sim_tinyx4.h
... that were previously offered but not taken.  Now packaged as a PR.
=> Two "hardware" changes

simavr/sim/sim_interrupts.c
This PR fixes an issue that may cause some interrupts to be stuck in a 'pending' state forever without ever being serviced.
This bug arises when all of the following conditions are met:
- `avr_service_interrupts` is called with multiple pending interrupts in the `avr->interrupts->pending` queue.
- The interrupt at the front of the `pending` queue is not the highest-priority pending interrupt (i.e. there are other pending interrupts with lower `vector` values).
- The highest-priority interrupt is at the back of the `pending` queue.
When this sequence of events arises, an off-by-one error is triggered and the interrupt at the front of the `pending` queue is swapped to an index 1 beyond the end of the queue while in a `pending` state, and is therefore never serviced.
This fix only triggers …
=> Fix interrupt servicing with multiple pending interrupts

simavr/sim/run_avr.c
Change the usage message shown by run-avr to show when tracing is disabled.
=> Show whether instruction tracing is enabled in the usage message.

.gitignore, simavr/.gitignore
Update `.gitignore` to so git ignores the `.vscode` folder.
=> Ignore Visual Studio Code folder

simavr/sim/sim_elf.c
Previously the Section Table was used, causing problems when using non-default section names.  Fixes upstream #484 "Located sections are ignored by simavr".
=> Use the Program Header Table to control loading from ELF files.

simavr/sim/sim_elf.c
=> Fix duplicate VCD names.

simavr/sim/sim_gdb.c
... by running a burst of instructions before checking for input from GDB.  Discussed in #489.
=> Speed execution with GDB 

examples/Makefile.opengl
Build probleme with ubuntu, I've to add that to the linker
=> add  -lGL -lGLU to the Makefile

simavr/sim/sim_hex.c
=> Include load base in all address checks when loading firmware

simavr/cores/sim_tiny2313.c, simavr/cores/sim_tiny2313a.c, simavr/cores/sim_tiny4313.c, simavr/cores/sim_tinyx4.c, simavr/cores/sim_tinyx4.h, simavr/cores/sim_tinyx5.c, simavr/cores/sim_tinyx5.h, simavr/sim/avr_usi.c, simavr/sim/avr_usi.h, tests/attiny2313a_usi.c, tests/attiny84_usi.c, tests/test_attiny2313a_usi.c, tests/tests.c
... somewhat modified and with a test added.  USI is the "Universal Serial Bus" peripheral found in some Tinys.  This fixes issue #326.
=> Add USI implementation from Jarrett Billingsley's fork

examples/board_simduino/README, examples/board_simduino/simduino.c
This is relatively insignificant and not a commit that affects functionality, but this typo annoys me during usage so it might as well be fixed!
=> Fix "booloader" typo
